/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const GlucoseUnit = IDL.Variant({
  'mmoll' : IDL.Null,
  'mgdl' : IDL.Null,
});
export const AddGlucoseInput = IDL.Record({
  'readingTime' : Timestamp,
  'value' : IDL.Float64,
  'unit' : GlucoseUnit,
  'notes' : IDL.Text,
});
export const UserId = IDL.Principal;
export const GlucoseEntry = IDL.Record({
  'id' : IDL.Nat,
  'readingTime' : Timestamp,
  'value' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'unit' : GlucoseUnit,
  'notes' : IDL.Text,
});
export const Result__1_2 = IDL.Variant({
  'ok' : GlucoseEntry,
  'err' : IDL.Text,
});
export const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null });
export const AddWeightInput = IDL.Record({
  'value' : IDL.Float64,
  'unit' : WeightUnit,
  'recordedAt' : Timestamp,
  'notes' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'unit' : WeightUnit,
  'recordedAt' : Timestamp,
  'notes' : IDL.Text,
});
export const Result__1_1 = IDL.Variant({
  'ok' : WeightEntry,
  'err' : IDL.Text,
});
export const UserDetail = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'weightEntries' : IDL.Vec(WeightEntry),
  'glucoseEntries' : IDL.Vec(GlucoseEntry),
});
export const Result__3_1 = IDL.Variant({ 'ok' : UserDetail, 'err' : IDL.Text });
export const UserSummary = IDL.Record({
  'id' : UserId,
  'entryCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const Result__3 = IDL.Variant({
  'ok' : IDL.Vec(UserSummary),
  'err' : IDL.Text,
});
export const HealthPage = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'weightEntries' : IDL.Vec(WeightEntry),
  'glucoseEntries' : IDL.Vec(GlucoseEntry),
});
export const Result__1 = IDL.Variant({ 'ok' : HealthPage, 'err' : IDL.Text });
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const User = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const Result__2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const NotificationKind = IDL.Variant({
  'weight' : IDL.Null,
  'glucose' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'value' : IDL.Float64,
  'userId' : UserId,
  'kind' : NotificationKind,
  'unit' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Timestamp,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Vec(Notification),
  'err' : IDL.Text,
});
export const LoginInput = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const AuthResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : User }),
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const SignupInput = IDL.Record({
  'password' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGlucoseEntry' : IDL.Func([IDL.Text, AddGlucoseInput], [Result__1_2], []),
  'addWeightEntry' : IDL.Func([IDL.Text, AddWeightInput], [Result__1_1], []),
  'adminGetUserDetail' : IDL.Func([IDL.Text, UserId], [Result__3_1], ['query']),
  'adminListUsers' : IDL.Func([IDL.Text], [Result__3], ['query']),
  'getAllHealthEntries' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [Result__1],
      ['query'],
    ),
  'getMe' : IDL.Func([IDL.Text], [Result__2], ['query']),
  'getMyHealthEntries' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [Result__1],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([IDL.Text], [Result_2], ['query']),
  'getUnreadNotifications' : IDL.Func([IDL.Text], [Result_1], ['query']),
  'getUserHealthEntries' : IDL.Func(
      [IDL.Text, UserId, IDL.Nat, IDL.Nat],
      [Result__1],
      ['query'],
    ),
  'initAdmin' : IDL.Func([], [IDL.Text], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([LoginInput], [AuthResult], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'markNotificationsRead' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [Result],
      [],
    ),
  'resetAdmin' : IDL.Func([], [IDL.Text], []),
  'signup' : IDL.Func([SignupInput], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const GlucoseUnit = IDL.Variant({ 'mmoll' : IDL.Null, 'mgdl' : IDL.Null });
  const AddGlucoseInput = IDL.Record({
    'readingTime' : Timestamp,
    'value' : IDL.Float64,
    'unit' : GlucoseUnit,
    'notes' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const GlucoseEntry = IDL.Record({
    'id' : IDL.Nat,
    'readingTime' : Timestamp,
    'value' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'unit' : GlucoseUnit,
    'notes' : IDL.Text,
  });
  const Result__1_2 = IDL.Variant({ 'ok' : GlucoseEntry, 'err' : IDL.Text });
  const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null });
  const AddWeightInput = IDL.Record({
    'value' : IDL.Float64,
    'unit' : WeightUnit,
    'recordedAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const WeightEntry = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'unit' : WeightUnit,
    'recordedAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const Result__1_1 = IDL.Variant({ 'ok' : WeightEntry, 'err' : IDL.Text });
  const UserDetail = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'weightEntries' : IDL.Vec(WeightEntry),
    'glucoseEntries' : IDL.Vec(GlucoseEntry),
  });
  const Result__3_1 = IDL.Variant({ 'ok' : UserDetail, 'err' : IDL.Text });
  const UserSummary = IDL.Record({
    'id' : UserId,
    'entryCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const Result__3 = IDL.Variant({
    'ok' : IDL.Vec(UserSummary),
    'err' : IDL.Text,
  });
  const HealthPage = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'weightEntries' : IDL.Vec(WeightEntry),
    'glucoseEntries' : IDL.Vec(GlucoseEntry),
  });
  const Result__1 = IDL.Variant({ 'ok' : HealthPage, 'err' : IDL.Text });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const User = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : Role,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const Result__2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const NotificationKind = IDL.Variant({
    'weight' : IDL.Null,
    'glucose' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'value' : IDL.Float64,
    'userId' : UserId,
    'kind' : NotificationKind,
    'unit' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Timestamp,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Vec(Notification),
    'err' : IDL.Text,
  });
  const LoginInput = IDL.Record({ 'password' : IDL.Text, 'email' : IDL.Text });
  const AuthResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : User }),
    'err' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const SignupInput = IDL.Record({
    'password' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'addGlucoseEntry' : IDL.Func(
        [IDL.Text, AddGlucoseInput],
        [Result__1_2],
        [],
      ),
    'addWeightEntry' : IDL.Func([IDL.Text, AddWeightInput], [Result__1_1], []),
    'adminGetUserDetail' : IDL.Func(
        [IDL.Text, UserId],
        [Result__3_1],
        ['query'],
      ),
    'adminListUsers' : IDL.Func([IDL.Text], [Result__3], ['query']),
    'getAllHealthEntries' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Result__1],
        ['query'],
      ),
    'getMe' : IDL.Func([IDL.Text], [Result__2], ['query']),
    'getMyHealthEntries' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Result__1],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([IDL.Text], [Result_2], ['query']),
    'getUnreadNotifications' : IDL.Func([IDL.Text], [Result_1], ['query']),
    'getUserHealthEntries' : IDL.Func(
        [IDL.Text, UserId, IDL.Nat, IDL.Nat],
        [Result__1],
        ['query'],
      ),
    'initAdmin' : IDL.Func([], [IDL.Text], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([LoginInput], [AuthResult], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'markNotificationsRead' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [Result],
        [],
      ),
    'resetAdmin' : IDL.Func([], [IDL.Text], []),
    'signup' : IDL.Func([SignupInput], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };