/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddGlucoseInput {
  'readingTime' : Timestamp,
  'value' : number,
  'unit' : GlucoseUnit,
  'notes' : string,
}
export interface AddWeightInput {
  'value' : number,
  'unit' : WeightUnit,
  'recordedAt' : Timestamp,
  'notes' : string,
}
export type AuthResult = { 'ok' : { 'token' : string, 'user' : User } } |
  { 'err' : string };
export interface GlucoseEntry {
  'id' : bigint,
  'readingTime' : Timestamp,
  'value' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'unit' : GlucoseUnit,
  'notes' : string,
}
export type GlucoseUnit = { 'mmoll' : null } |
  { 'mgdl' : null };
export interface HealthPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'weightEntries' : Array<WeightEntry>,
  'glucoseEntries' : Array<GlucoseEntry>,
}
export interface LoginInput { 'password' : string, 'email' : string }
export interface Notification {
  'id' : bigint,
  'userName' : string,
  'value' : number,
  'userId' : UserId,
  'kind' : NotificationKind,
  'unit' : string,
  'isRead' : boolean,
  'timestamp' : Timestamp,
}
export type NotificationKind = { 'weight' : null } |
  { 'glucose' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : Array<Notification> } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result__1 = { 'ok' : HealthPage } |
  { 'err' : string };
export type Result__1_1 = { 'ok' : WeightEntry } |
  { 'err' : string };
export type Result__1_2 = { 'ok' : GlucoseEntry } |
  { 'err' : string };
export type Result__2 = { 'ok' : User } |
  { 'err' : string };
export type Result__3 = { 'ok' : Array<UserSummary> } |
  { 'err' : string };
export type Result__3_1 = { 'ok' : UserDetail } |
  { 'err' : string };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface SignupInput {
  'password' : string,
  'fullName' : string,
  'email' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : Role,
  'fullName' : string,
  'email' : string,
}
export interface UserDetail {
  'id' : UserId,
  'createdAt' : Timestamp,
  'fullName' : string,
  'email' : string,
  'weightEntries' : Array<WeightEntry>,
  'glucoseEntries' : Array<GlucoseEntry>,
}
export type UserId = Principal;
export interface UserSummary {
  'id' : UserId,
  'entryCount' : bigint,
  'createdAt' : Timestamp,
  'fullName' : string,
  'email' : string,
}
export interface WeightEntry {
  'id' : bigint,
  'value' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'unit' : WeightUnit,
  'recordedAt' : Timestamp,
  'notes' : string,
}
export type WeightUnit = { 'kg' : null } |
  { 'lbs' : null };
export interface _SERVICE {
  'addGlucoseEntry' : ActorMethod<[string, AddGlucoseInput], Result__1_2>,
  'addWeightEntry' : ActorMethod<[string, AddWeightInput], Result__1_1>,
  'adminGetUserDetail' : ActorMethod<[string, UserId], Result__3_1>,
  'adminListUsers' : ActorMethod<[string], Result__3>,
  'getAllHealthEntries' : ActorMethod<[string, bigint, bigint], Result__1>,
  'getMe' : ActorMethod<[string], Result__2>,
  'getMyHealthEntries' : ActorMethod<[string, bigint, bigint], Result__1>,
  'getUnreadNotificationCount' : ActorMethod<[string], Result_2>,
  'getUnreadNotifications' : ActorMethod<[string], Result_1>,
  'getUserHealthEntries' : ActorMethod<
    [string, UserId, bigint, bigint],
    Result__1
  >,
  'initAdmin' : ActorMethod<[], string>,
  'isAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[LoginInput], AuthResult>,
  'logout' : ActorMethod<[string], undefined>,
  'markNotificationsRead' : ActorMethod<[string, Array<bigint>], Result>,
  'resetAdmin' : ActorMethod<[], string>,
  'signup' : ActorMethod<[SignupInput], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];