/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LoginInput {
    password: string;
    email: string;
}
export type Timestamp = bigint;
export type Result__1_1 = {
    __kind__: "ok";
    ok: WeightEntry;
} | {
    __kind__: "err";
    err: string;
};
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result__3 = {
    __kind__: "ok";
    ok: Array<UserSummary>;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    fullName: string;
    email: string;
}
export type Result__1 = {
    __kind__: "ok";
    ok: HealthPage;
} | {
    __kind__: "err";
    err: string;
};
export type Result__3_1 = {
    __kind__: "ok";
    ok: UserDetail;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Array<Notification>;
} | {
    __kind__: "err";
    err: string;
};
export interface HealthPage {
    total: bigint;
    offset: bigint;
    limit: bigint;
    weightEntries: Array<WeightEntry>;
    glucoseEntries: Array<GlucoseEntry>;
}
export interface GlucoseEntry {
    id: bigint;
    readingTime: Timestamp;
    value: number;
    userId: UserId;
    createdAt: Timestamp;
    unit: GlucoseUnit;
    notes: string;
}
export type UserId = Principal;
export interface UserDetail {
    id: UserId;
    createdAt: Timestamp;
    fullName: string;
    email: string;
    weightEntries: Array<WeightEntry>;
    glucoseEntries: Array<GlucoseEntry>;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface AddWeightInput {
    value: number;
    unit: WeightUnit;
    recordedAt: Timestamp;
    notes: string;
}
export interface UserSummary {
    id: UserId;
    entryCount: bigint;
    createdAt: Timestamp;
    fullName: string;
    email: string;
}
export type Result__2 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1_2 = {
    __kind__: "ok";
    ok: GlucoseEntry;
} | {
    __kind__: "err";
    err: string;
};
export interface Notification {
    id: bigint;
    userName: string;
    value: number;
    userId: UserId;
    kind: NotificationKind;
    unit: string;
    isRead: boolean;
    timestamp: Timestamp;
}
export type AuthResult = {
    __kind__: "ok";
    ok: {
        token: string;
        user: User;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface WeightEntry {
    id: bigint;
    value: number;
    userId: UserId;
    createdAt: Timestamp;
    unit: WeightUnit;
    recordedAt: Timestamp;
    notes: string;
}
export interface AddGlucoseInput {
    readingTime: Timestamp;
    value: number;
    unit: GlucoseUnit;
    notes: string;
}
export interface SignupInput {
    password: string;
    fullName: string;
    email: string;
}
export enum GlucoseUnit {
    mmoll = "mmoll",
    mgdl = "mgdl"
}
export enum NotificationKind {
    weight = "weight",
    glucose = "glucose"
}
export enum Role {
    admin = "admin",
    user = "user"
}
export enum WeightUnit {
    kg = "kg",
    lbs = "lbs"
}
export interface backendInterface {
    addGlucoseEntry(token: string, input: AddGlucoseInput): Promise<Result__1_2>;
    addWeightEntry(token: string, input: AddWeightInput): Promise<Result__1_1>;
    adminGetUserDetail(token: string, userId: UserId): Promise<Result__3_1>;
    adminListUsers(token: string): Promise<Result__3>;
    getAllHealthEntries(token: string, offset: bigint, limit: bigint): Promise<Result__1>;
    getMe(token: string): Promise<Result__2>;
    getMyHealthEntries(token: string, offset: bigint, limit: bigint): Promise<Result__1>;
    getUnreadNotificationCount(token: string): Promise<Result_2>;
    getUnreadNotifications(token: string): Promise<Result_1>;
    getUserHealthEntries(token: string, userId: UserId, offset: bigint, limit: bigint): Promise<Result__1>;
    initAdmin(): Promise<string>;
    isAdmin(): Promise<boolean>;
    login(input: LoginInput): Promise<AuthResult>;
    logout(token: string): Promise<void>;
    markNotificationsRead(token: string, ids: Array<bigint>): Promise<Result>;
    resetAdmin(): Promise<string>;
    signup(input: SignupInput): Promise<AuthResult>;
}
import type { AddGlucoseInput as _AddGlucoseInput, AddWeightInput as _AddWeightInput, AuthResult as _AuthResult, GlucoseEntry as _GlucoseEntry, GlucoseUnit as _GlucoseUnit, HealthPage as _HealthPage, Notification as _Notification, NotificationKind as _NotificationKind, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result__1 as _Result__1, Result__1_1 as _Result__1_1, Result__1_2 as _Result__1_2, Result__2 as _Result__2, Result__3 as _Result__3, Result__3_1 as _Result__3_1, Role as _Role, Timestamp as _Timestamp, User as _User, UserDetail as _UserDetail, UserId as _UserId, UserSummary as _UserSummary, WeightEntry as _WeightEntry, WeightUnit as _WeightUnit } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGlucoseEntry(arg0: string, arg1: AddGlucoseInput): Promise<Result__1_2> {
        if (this.processError) {
            try {
                const result = await this.actor.addGlucoseEntry(arg0, to_candid_AddGlucoseInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result__1_2_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGlucoseEntry(arg0, to_candid_AddGlucoseInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result__1_2_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addWeightEntry(arg0: string, arg1: AddWeightInput): Promise<Result__1_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, to_candid_AddWeightInput_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result__1_1_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, to_candid_AddWeightInput_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result__1_1_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetUserDetail(arg0: string, arg1: UserId): Promise<Result__3_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserDetail(arg0, arg1);
                return from_candid_Result__3_1_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserDetail(arg0, arg1);
            return from_candid_Result__3_1_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: string): Promise<Result__3> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(arg0);
                return from_candid_Result__3_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(arg0);
            return from_candid_Result__3_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHealthEntries(arg0: string, arg1: bigint, arg2: bigint): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHealthEntries(arg0, arg1, arg2);
                return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHealthEntries(arg0, arg1, arg2);
            return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMe(arg0: string): Promise<Result__2> {
        if (this.processError) {
            try {
                const result = await this.actor.getMe(arg0);
                return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMe(arg0);
            return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyHealthEntries(arg0: string, arg1: bigint, arg2: bigint): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHealthEntries(arg0, arg1, arg2);
                return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHealthEntries(arg0, arg1, arg2);
            return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount(arg0);
                return from_candid_Result_2_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount(arg0);
            return from_candid_Result_2_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotifications(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotifications(arg0);
                return from_candid_Result_1_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotifications(arg0);
            return from_candid_Result_1_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserHealthEntries(arg0: string, arg1: UserId, arg2: bigint, arg3: bigint): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserHealthEntries(arg0, arg1, arg2, arg3);
                return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserHealthEntries(arg0, arg1, arg2, arg3);
            return from_candid_Result__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async login(arg0: LoginInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_AuthResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_AuthResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async markNotificationsRead(arg0: string, arg1: Array<bigint>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead(arg0, arg1);
                return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead(arg0, arg1);
            return from_candid_Result_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdmin();
            return result;
        }
    }
    async signup(arg0: SignupInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.signup(arg0);
                return from_candid_AuthResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signup(arg0);
            return from_candid_AuthResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_GlucoseEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlucoseEntry): GlucoseEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_GlucoseUnit_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GlucoseUnit): GlucoseUnit {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_HealthPage_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthPage): HealthPage {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationKind_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_1): Result__1_1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_2_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1_2): Result__1_2 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Result__2_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__2): Result__2 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result__3_1_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__3_1): Result__3_1 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result__3_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__3): Result__3 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserDetail_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserDetail): UserDetail {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_User_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_WeightEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightEntry): WeightEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WeightUnit_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightUnit): WeightUnit {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    value: number;
    userId: _UserId;
    createdAt: _Timestamp;
    unit: _WeightUnit;
    recordedAt: _Timestamp;
    notes: string;
}): {
    id: bigint;
    value: number;
    userId: UserId;
    createdAt: Timestamp;
    unit: WeightUnit;
    recordedAt: Timestamp;
    notes: string;
} {
    return {
        id: value.id,
        value: value.value,
        userId: value.userId,
        createdAt: value.createdAt,
        unit: from_candid_WeightUnit_n19(_uploadFile, _downloadFile, value.unit),
        recordedAt: value.recordedAt,
        notes: value.notes
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    fullName: string;
    email: string;
    weightEntries: Array<_WeightEntry>;
    glucoseEntries: Array<_GlucoseEntry>;
}): {
    id: UserId;
    createdAt: Timestamp;
    fullName: string;
    email: string;
    weightEntries: Array<WeightEntry>;
    glucoseEntries: Array<GlucoseEntry>;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        fullName: value.fullName,
        email: value.email,
        weightEntries: from_candid_vec_n25(_uploadFile, _downloadFile, value.weightEntries),
        glucoseEntries: from_candid_vec_n26(_uploadFile, _downloadFile, value.glucoseEntries)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    weightEntries: Array<_WeightEntry>;
    glucoseEntries: Array<_GlucoseEntry>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    weightEntries: Array<WeightEntry>;
    glucoseEntries: Array<GlucoseEntry>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        weightEntries: from_candid_vec_n25(_uploadFile, _downloadFile, value.weightEntries),
        glucoseEntries: from_candid_vec_n26(_uploadFile, _downloadFile, value.glucoseEntries)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    role: _Role;
    fullName: string;
    email: string;
}): {
    id: UserId;
    createdAt: Timestamp;
    role: Role;
    fullName: string;
    email: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        role: from_candid_Role_n37(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        email: value.email
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userName: string;
    value: number;
    userId: _UserId;
    kind: _NotificationKind;
    unit: string;
    isRead: boolean;
    timestamp: _Timestamp;
}): {
    id: bigint;
    userName: string;
    value: number;
    userId: UserId;
    kind: NotificationKind;
    unit: string;
    isRead: boolean;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        userName: value.userName,
        value: value.value,
        userId: value.userId,
        kind: from_candid_NotificationKind_n46(_uploadFile, _downloadFile, value.kind),
        unit: value.unit,
        isRead: value.isRead,
        timestamp: value.timestamp
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    user: _User;
}): {
    token: string;
    user: User;
} {
    return {
        token: value.token,
        user: from_candid_User_n35(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    readingTime: _Timestamp;
    value: number;
    userId: _UserId;
    createdAt: _Timestamp;
    unit: _GlucoseUnit;
    notes: string;
}): {
    id: bigint;
    readingTime: Timestamp;
    value: number;
    userId: UserId;
    createdAt: Timestamp;
    unit: GlucoseUnit;
    notes: string;
} {
    return {
        id: value.id,
        readingTime: value.readingTime,
        value: value.value,
        userId: value.userId,
        createdAt: value.createdAt,
        unit: from_candid_GlucoseUnit_n9(_uploadFile, _downloadFile, value.unit),
        notes: value.notes
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mmoll: null;
} | {
    mgdl: null;
}): GlucoseUnit {
    return "mmoll" in value ? GlucoseUnit.mmoll : "mgdl" in value ? GlucoseUnit.mgdl : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WeightEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WeightEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WeightEntry_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    lbs: null;
}): WeightUnit {
    return "kg" in value ? WeightUnit.kg : "lbs" in value ? WeightUnit.lbs : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserDetail;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserDetail;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserDetail_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserSummary>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserSummary>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HealthPage;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: HealthPage;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_HealthPage_n31(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Notification>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Notification>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n43(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: null;
} | {
    glucose: null;
}): NotificationKind {
    return "weight" in value ? NotificationKind.weight : "glucose" in value ? NotificationKind.glucose : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        user: _User;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        user: User;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GlucoseEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GlucoseEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GlucoseEntry_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeightEntry>): Array<WeightEntry> {
    return value.map((x)=>from_candid_WeightEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GlucoseEntry>): Array<GlucoseEntry> {
    return value.map((x)=>from_candid_GlucoseEntry_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n44(_uploadFile, _downloadFile, x));
}
function to_candid_AddGlucoseInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddGlucoseInput): _AddGlucoseInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AddWeightInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddWeightInput): _AddWeightInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_GlucoseUnit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlucoseUnit): _GlucoseUnit {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_WeightUnit_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): _WeightUnit {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    unit: WeightUnit;
    recordedAt: Timestamp;
    notes: string;
}): {
    value: number;
    unit: _WeightUnit;
    recordedAt: _Timestamp;
    notes: string;
} {
    return {
        value: value.value,
        unit: to_candid_WeightUnit_n13(_uploadFile, _downloadFile, value.unit),
        recordedAt: value.recordedAt,
        notes: value.notes
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    readingTime: Timestamp;
    value: number;
    unit: GlucoseUnit;
    notes: string;
}): {
    readingTime: _Timestamp;
    value: number;
    unit: _GlucoseUnit;
    notes: string;
} {
    return {
        readingTime: value.readingTime,
        value: value.value,
        unit: to_candid_GlucoseUnit_n3(_uploadFile, _downloadFile, value.unit),
        notes: value.notes
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): {
    kg: null;
} | {
    lbs: null;
} {
    return value == WeightUnit.kg ? {
        kg: null
    } : value == WeightUnit.lbs ? {
        lbs: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GlucoseUnit): {
    mmoll: null;
} | {
    mgdl: null;
} {
    return value == GlucoseUnit.mmoll ? {
        mmoll: null
    } : value == GlucoseUnit.mgdl ? {
        mgdl: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
